app:
  # 应用端口
  port: 9527

# 数据库配置
database:
  host: 192.168.3.19    # 数据库主机
  port: 3306    # 数据库端口
  user: root    # 数据库用户名
  password: 111111    # 数据库密码
  dbname: homework4    # 数据库名

# Redis 配置
redis:
  host: 192.168.3.19    # Redis 主机
  port: 6379    # Redis 端口
  password: 111111    # Redis 密码 
  db: 0    # Redis 数据库索引

jwt:
  secret: dadf4f41-53ea-4f81-b459-e31d22c474dc    # JWT 密钥
  expires: 24    # JWT 过期时间 单位小时